import "./globals.css";

export const metadata = {
  title: "Atqiya Haydar — Software developer & ui/ux designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="raleway-regular">
        {children}
      </body>
    </html>
  );
}
